import { create } from 'zustand'

export const useDatatableStore = create((set) => ({
  theme: '',
  title: '',
  cols: [],
  rows: [],
  allRows: [],
  filteredRows: [],
  totalRows: 0,
  minRowIndex: 1,
  maxRowIndex: 1,
  pages: [],
  pageSize: 5,
  pageCount: 1,
  pageIndex: 1,
  pageGroupIndex: 1,
  maxPageCount: 5,
  minPageIndex: 1,
  maxPageIndex: 1,
  showLess: false,
  showMore: false,
  sortField: '',
  sortDir: 0,
  searchText: '',
  rowLabel: 'records',
  setTheme: (theme) => set({ theme }),
  setTitle: (title) => set({ title }),
  setSearchText: (searchText) => set({ searchText }),
  setSortField: (sortField) => set({ sortField }),
  setSortDir: (sortDir) => set({ sortDir }),
  setCols: (cols) => set({ cols }),
  setRows: (rows) => set({ rows }),
  setAllRows: (allRows) => set({ allRows }),
  setFilteredRows: (filteredRows) => set({ filteredRows }),
  setTotalRows: (totalRows) => set({ totalRows }),
  setMinRowIndex: (minRowIndex) => set({ minRowIndex }),
  setMaxRowIndex: (maxRowIndex) => set({ maxRowIndex }),
  setPages: (pages) => set({ pages }),
  setPageSize: (pageSize) => set({ pageSize }),
  setPageCount: (pageCount) => set({ pageCount }),
  setPageIndex: (pageIndex) => set({ pageIndex }),
  setPageGroupIndex: (pageGroupIndex) => set({ pageGroupIndex }),
  setMinPageIndex: (minPageIndex) => set({ minPageIndex }),
  setMaxPageIndex: (maxPageIndex) => set({ maxPageIndex }),
  setShowLess: (showLess) => set({ showLess }),
  setShowMore: (showMore) => set({ showMore })
}))
